import { StaticImageData } from "next/image";
import defaultImg from "../images-default/default-1.png";
import defaultImg2 from "../images-default/default-2.png";
import defaultImg3 from "../images-default/default-3.png";

export const mockSliderData = [
  {
    img: defaultImg3,
    title:
      "Шины летние 255/35/16 с дисками yokohama Шины летние 255/35/16 с дисками yokohama Шины летние 255/35/16 с дисками yokohama Шины летние 255/35/16 с дисками yokohama",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg2,
    title: "Книги Л.Н. Толстого 4 тома, 2 книги Абая К.",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg,
    title: "Аллюминивая кружка",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg3,
    title: "Шины летние 255/35/16 с дисками yokohama",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg2,
    title: "Книги Л.Н. Толстого 4 тома, 2 книги Абая К.",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg,
    title: "Аллюминивая кружка",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg3,
    title: "Шины летние 255/35/16 с дисками yokohama",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg2,
    title: "Книги Л.Н. Толстого 4 тома, 2 книги Абая К.",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg,
    title: "Аллюминивая кружка",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg3,
    title: "Шины летние 255/35/16 с дисками yokohama",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg2,
    title: "Книги Л.Н. Толстого 4 тома, 2 книги Абая К.",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg,
    title: "Аллюминивая кружка",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg3,
    title: "Шины летние 255/35/16 с дисками yokohama",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg2,
    title: "Книги Л.Н. Толстого 4 тома, 2 книги Абая К.",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg,
    title: "Аллюминивая кружка",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg3,
    title: "Шины летние 255/35/16 с дисками yokohama",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg2,
    title: "Книги Л.Н. Толстого 4 тома, 2 книги Абая К.",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg,
    title: "Аллюминивая кружка",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg3,
    title: "Шины летние 255/35/16 с дисками yokohama",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg2,
    title: "Книги Л.Н. Толстого 4 тома, 2 книги Абая К.",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg,
    title: "Аллюминивая кружка",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg3,
    title: "Шины летние 255/35/16 с дисками yokohama",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg2,
    title: "Книги Л.Н. Толстого 4 тома, 2 книги Абая К.",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
  {
    img: defaultImg,
    title: "Аллюминивая кружка",
    city: "Алматы",
    date: "Вчера 19:57",
    sum: "80 000₸",
  },
];
